### PR TITLE
R4.1: add fc38

### PR DESCRIPTION
**Pull request by rustybird**

### CODE REVIEW

**Comment by fepitre** [comment]
I'm holding it until Fedora 38 is out and stable.

**Comment by rustybird** [comment]
Stable as in, moved from templates-itl-testing to templates-itl? Or just the upstream Fedora 38 release date (~ 2023-04-18)

**Comment by fepitre** [comment]
Yes, as there is several known bugs and I want it to be in stable first. @marmarek?

**Comment by marmarek** [comment]
The current fedora-38 template still has issues, but IMO it doesn't block building other packages for fc38 already.

**Pull request merged**
